"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.IFraxCanoToken__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "",
                type: "address"
            },
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        name: "exchangeCanonicalForOld",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "nonpayable",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "",
                type: "address"
            },
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        name: "exchangeOldForCanonical",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "nonpayable",
        type: "function"
    },
];
var IFraxCanoToken__factory = /** @class */ (function () {
    function IFraxCanoToken__factory() {
    }
    IFraxCanoToken__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IFraxCanoToken__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IFraxCanoToken__factory.abi = _abi;
    return IFraxCanoToken__factory;
}());
exports.IFraxCanoToken__factory = IFraxCanoToken__factory;
