"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.ISwapToken__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
            {
                internalType: "address[]",
                name: "",
                type: "address[]"
            },
            {
                internalType: "address",
                name: "",
                type: "address"
            },
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        name: "swapExactTokensForTokens",
        outputs: [
            {
                internalType: "uint256[]",
                name: "",
                type: "uint256[]"
            },
        ],
        stateMutability: "nonpayable",
        type: "function"
    },
];
var ISwapToken__factory = /** @class */ (function () {
    function ISwapToken__factory() {
    }
    ISwapToken__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    ISwapToken__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    ISwapToken__factory.abi = _abi;
    return ISwapToken__factory;
}());
exports.ISwapToken__factory = ISwapToken__factory;
